### ISSUE TITLE
Use of gnu/time command in regression

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2050]
I am working on some changes to optimize memory use and noticing some rather strange results on regression. The memory use does go down for small and medium sized tests but for larger tests the reported memory use almost doubles which isn't making much sense. On further investigation it turns out that there's a reported bug in gnu/time command. More information here -

https://forums.whirlpool.net.au/archive/1693957
https://groups.google.com/g/gnu.utils.help/c/u1MOsHL4bhg
https://debiantutorials.org/question/what-does-the-linux-command-usr-bin-time-show-in-the-maxresident-field-3643/

But all these discussions are rather old (some starting in 2010). Before I spend more cycles investigating the root cause of the discrepancy in my changes, could either of you please confirm that this is or is not an issue on current Ubuntu's default /usr/bin/time command.

Thanks!!

**Comment by hs-apotell** [comment]
Here are both the PRs https://github.com/chipsalliance/UHDM/pull/540 & https://github.com/chipsalliance/Surelog/pull/2067. The only interesting changes are in four files. Every other change is fallout of changing the APIs.

[templates/SymbolFactory.h](https://github.com/chipsalliance/UHDM/pull/540/files#diff-3a8ad7aac7a2658e7710769d849d0d80676ad84f8f86b4a439fae979aa1cadc6)
[templates/SymbolFactory.cpp](https://github.com/chipsalliance/UHDM/pull/540/files#diff-03a0f25abda19de672c6ec94e20710efeef2c056168527b85b78d84cc47ee840)
[src/SourceCompile/SymbolTable.h](https://github.com/chipsalliance/Surelog/pull/2067/files#diff-ad63e6d1ba8592cb4ef81d141631ed350ec26e75fabdcd77796fb725c4667210)
[src/SourceCompile/SymbolTable.cpp](https://github.com/chipsalliance/Surelog/pull/2067/files#diff-b1050ebfc78a47ae865332f3b25da7963382f92e01d5bbeb1c1da12882756ec2)

I have no new allocations except the fact that I am allocating 1MB buffers for `SymbolTable` & `SymbolFactory`. I do have an assumption that registered symbols are persistent and `SymbolTable` & `SymbolFactory` instances are never deleted unless the entire design is being purged. `SymbolTable` doesn't clone the registered strings when creating clones (via the copy constructor). `SymbolTable` instances share the same backend cache store. I expected the memory requirement to shrink for larger designs since we aren't duplicating symbol table storage but I have completely opposite affect. Here are some of the numbers I have collected from a few runs.

Column 1: Test Name
Column 2 & 3: Surelog Master runs
Column 4 & 5: Surelog Master + https://github.com/chipsalliance/UHDM/pull/540 + https://github.com/chipsalliance/Surelog/pull/2067
Column 5: Column 2 - Column 4
Column 6: Column 3 - Column 4
Column 7: Column 2 - Column 5
Column 6: Column 3 - Column 5

Full data set attached. [Perf.txt](https://github.com/chipsalliance/Surelog/files/7342167/Perf.txt)

```
+-----------------------------+  +-----------------------+----------------------+  +-----------------+----------------+  +---------------+---------------+--------------+--------------+
|                             |  | # 203: Surelog Master | #204: Surelog Master |  | #206: Optimized | #11: Optimized |  | #203 vs. #206 | #204 vs. #206 | #203 vs. #11 | #204 vs. #11 |
+-----------------------------+  +-----------------------+----------------------+  +-----------------+----------------+  +---------------+---------------+--------------+--------------+
| TESTNAME                    |  | MEM(Mb)               | MEM(Mb)              |  | MEM(Mb)         | MEM(Mb)        |  | MEM(Mb)       | MEM(Mb)       | MEM(Mb)      | MEM(Mb)      |
+-----------------------------+  +-----------------------+----------------------+  +-----------------+----------------+  +---------------+---------------+--------------+--------------+
| Google                      |  |                  1908 |                 1926 |  |            2170 |           2186 |  |          -262 |          -244 |         -278 |         -260 |
| Icarus                      |  |                   165 |                  168 |  |             454 |            385 |  |          -289 |          -286 |         -220 |         -217 |
| Unisim                      |  |                  1165 |                 1167 |  |            1274 |           1275 |  |          -109 |          -107 |         -110 |         -108 |
| UtdSV                       |  |                   183 |                  182 |  |             292 |            329 |  |          -109 |          -110 |         -146 |         -147 |
| Verilator                   |  |                   626 |                  622 |  |             938 |            934 |  |          -312 |          -316 |         -308 |         -312 |
| Yosys                       |  |                   169 |                  168 |  |             270 |            281 |  |          -101 |          -102 |         -112 |         -113 |
| YosysTests                  |  |                   837 |                  834 |  |            1497 |           1397 |  |          -660 |          -663 |         -560 |         -563 |
+-----------------------------+  +-----------------------+----------------------+  +-----------------+----------------+  +---------------+---------------+--------------+--------------+
```

I have reviewed my changes a number of times and found nothing obviously out of order. Appreciate a quick glance to see if either of you can spot something that I obviously overlooked. If not, I will spend some time setting up a Linux box and doing some digging (I have been using a VM on Windows so far and it gets unresponsive if I am building debug).

**Comment by alaindargelas** [comment]
I get it, those are most of the designs running in "batch" mode.It means one instance of Surelog executable is running 100s of distincts designs in a batch fashion in the same executable.The original implemention of Surelog release 99% of its memory in between designs, your new implementation has a huge leak (Maybe the Symbol Table) that keeps accumulating in between each design.


    On Wednesday, October 13, 2021, 06:17:12 PM PDT, HS ***@***.***> wrote:  
 
 


Here are both the PRs chipsalliance/UHDM#540 & #2067. The only interesting changes are in four files. Every other change is fallout of changing the APIs.

templates/SymbolFactory.h
templates/SymbolFactory.cpp
src/SourceCompile/SymbolTable.h
src/SourceCompile/SymbolTable.cpp

I have no new allocations except the fact that I am allocating 1MB buffers for SymbolTable & SymbolFactory. I do have an assumption that registered symbols are persistent and SymbolTable & SymbolFactory instances are never deleted unless the entire design is being purged. SymbolTable doesn't clone the registered strings when creating clones (via the copy constructor). SymbolTable instances share the same backend cache store. I expected the memory requirement to shrink for larger designs since we aren't duplicating symbol table storage but I have completely opposite affect. Here are some of the numbers I have collected from a few runs.

Column 1: Test Name
Column 2 & 3: Surelog Master runs
Column 4 & 5: Surelog Master + chipsalliance/UHDM#540 + #2067
Column 5: Column 2 - Column 4
Column 6: Column 3 - Column 4
Column 7: Column 2 - Column 5
Column 6: Column 3 - Column 5

Full data set attached. Perf.txt
+-----------------------------+  +-----------------------+----------------------+  +-----------------+----------------+  +---------------+---------------+--------------+--------------+
|                             |  | # 203: Surelog Master | #204: Surelog Master |  | #206: Optimized | #11: Optimized |  | #203 vs. #206 | #204 vs. #206 | #203 vs. #11 | #204 vs. #11 |
+-----------------------------+  +-----------------------+----------------------+  +-----------------+----------------+  +---------------+---------------+--------------+--------------+
| TESTNAME                    |  | MEM(Mb)               | MEM(Mb)              |  | MEM(Mb)         | MEM(Mb)        |  | MEM(Mb)       | MEM(Mb)       | MEM(Mb)      | MEM(Mb)      |
+-----------------------------+  +-----------------------+----------------------+  +-----------------+----------------+  +---------------+---------------+--------------+--------------+
| Google                      |  |                  1908 |                 1926 |  |            2170 |           2186 |  |          -262 |          -244 |         -278 |         -260 |
| Icarus                      |  |                   165 |                  168 |  |             454 |            385 |  |          -289 |          -286 |         -220 |         -217 |
| Unisim                      |  |                  1165 |                 1167 |  |            1274 |           1275 |  |          -109 |          -107 |         -110 |         -108 |
| UtdSV                       |  |                   183 |                  182 |  |             292 |            329 |  |          -109 |          -110 |         -146 |         -147 |
| Verilator                   |  |                   626 |                  622 |  |             938 |            934 |  |          -312 |          -316 |         -308 |         -312 |
| Yosys                       |  |                   169 |                  168 |  |             270 |            281 |  |          -101 |          -102 |         -112 |         -113 |
| YosysTests                  |  |                   837 |                  834 |  |            1497 |           1397 |  |          -660 |          -663 |         -560 |         -563 |
+-----------------------------+  +-----------------------+----------------------+  +-----------------+----------------+  +---------------+---------------+--------------+--------------+

I have reviewed my changes a number of times and found nothing obviously out of order. Appreciate a quick glance to see if either of you can spot something that I obviously overlooked. If not, I will spend some time setting up a Linux box and doing some digging (I have been using a VM on Windows so far and it gets unresponsive if I am building debug).

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
