### ISSUE TITLE
design visited twice in visitor logic

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2666]
For test AllBindings,the UHDM shows the `design` being visited twice. As it turns out, the `visited` set is being cleared every time the control comes back to `design` at indent 0. 

Is this really required? The generated output is misleading in some ways because of cloning. User can't be sure whether the specific instances in questions are clones or the same object.

Here's the script generating this code -
https://github.com/chipsalliance/UHDM/blob/ad9a41ed8dd74964401586b26843f3aca37fcab5/scripts/vpi_visitor_cpp.py#L29-L30

**Comment by alaindargelas** [comment]
Fixed by #2673
Note that now if you want to visit every node in the elaborated tree, since there is no reset in between the non elaborated and the elaborated tree,  you probably want to start your visitor not from the design level, but from the the topModules under the design object if you don't want to visit the vpiAllModules.
