### ISSUE TITLE
Missing package::typespecs, package::task_funcs for non-elaborated model

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#2686]
Test: ArianeElab

For the non-elaborated model, much of the data in `package` is missing.

**Comment by alaindargelas** [comment]
That is because it is strictly the same as the information in the elaborated model and it would be an unnecessary repeat. The only difference is the param_assign as I explained in the issue.
Please refer to the elaborated package vpiTopPackage for all of this information with the exception of the param_assign for your interest that you will find in the non-elaborated model vpiAllPackage
