### ISSUE TITLE
Parent ModuleDefinition for nested modules

### ISSUE THREAD

**Issue by hs-apotell** [chipsalliance/Surelog#3740]
Snippet From Test: Escape
```
module middle ();
  timeunit 10ps;
  timeprecision 1ps;
  wire a, b, c;
  module nested;
    assign c = a & b;
  endmodule
endmodule
```

How to get the `ModuleDefinition` for `middle` from the one for 'nested`. Looks like nested modules don't track their parent scope.

**Comment by Thomasb81** [comment]
It look like it is not possible. Also It seems to me there is no interest to track back parent module definition of this `nested` module which is not instantiate ...

Also for me this example compile because of implicit declaration of `wire a, b,c` inside module `nested`. But I don't think `wire a,b,c` from `middle` are connected to `wire a,b` and `c` from module `nested`. Because `nested` module is not instantiate in `middle`.
The source code only give the module definition of `nested`, but it remain not used.

The only interest to define module `nested` inside module `middle` is to restrict the visibility of this module name.

**Comment by Thomasb81** [comment]
I don't know if my view is shared, but object model as describe in chapter 37, is related to elaborate model only.

If Surelog expose both non-elaborated model and elaborated model using it could be seen to follow guide line discuss in chapter 3.12 on compilation and elaboration. Where non-elaborate model could be seen as the result of a compilation step.

For your intellisense / Go to declaration feature, I would more rely on a symbol table database that do not contain any binding information, which would probably be more suitable to deal with symbol visibility, to do a lookup and identify code position.

Ie:

```
module top1();
  module nested();
  endmodule
endmodule

module top2();
  module nested();
  endmodule
endmodule 
```

Definitively Intellisens / Go to declaration was not in the picture when people propose this SV data model. So not sure this data model is adequate for this usage...

**Comment by alaindargelas** [comment]
The nested module is still not part of the elaboration tree, @hs-apotell are you working on that?
